port: 8090

log:
  logPath: ./logs
  logName: imserver-console

mysql:
  user: root
  password: 123456
  address: 127.0.0.1:3306
  name: im_db

imApiDomain: http://127.0.0.1:9001
imAdminDomain: http://127.0.0.1:8090